### ISSUE TITLE
Properly display name of customer_id

### ISSUE THREAD

**Issue by blu-rayy** [blu-rayy/movie-rental#19]
ayusin lang yung error message, specify whom it is
![image](https://github.com/user-attachments/assets/ffd32a7a-fbc1-49df-bca0-fdfb961583b8)

**Comment by PatriciaThereseDamaso** [comment]
ano ito kapag valanga rented videos?

**Comment by PatriciaThereseDamaso** [comment]
walang*

**Comment by blu-rayy** [comment]
oo, ayusin lang error message with proper new lines tapos mas maganda if malalaman kung sino si customer (didisplay yung name)

**Comment by PatriciaThereseDamaso** [comment]
<img width="430" alt="Screenshot 2024-07-15 at 4 17 57 PM" src="https://github.com/user-attachments/assets/9d031d6c-b866-4cd1-bf93-1bd2ed5eca01">
